title: Code Fiesta
url: "https://www.codefiesta21.gov.sg"  # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/logo.ico     # TODO

# Site colors - copied from 
# https://drive.google.com/drive/u/0/folders/1nT_EYEe0sy5kFQB4iR3NNAubSPHDsVj-
colors:
  primary-color: '#695db1'      # violet
  secondary-color: '#b36898'    # beetroot
  media-colors:
    - title: media-color-one
      color: '#ed9d7a'          # orange
    - title: media-color-two
      color: '#9368a8'          # purple
    - title: media-color-three
      color: '#e5857e'          # salmon (?)
    - title: media-color-four
      color: '#f4ba76'          # orangey
    - title: media-color-five
      color: '#da7483'          # red/pink
    - title: media-color-six    # added from default; not sure if it'll show up
      color: '#4451b1'          # dark blue


collections:
  year_2021:
    output: true
resources_name: example-resource

description: Info homepage for the 2021 iteration of the Code Fiesta Hackathon organised in collaboration with GovTech Singapore

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
